### ISSUE TITLE
Hy there

### ISSUE THREAD

**Issue by AhsanulIslam** [qweas120/Data-Mining-Course-Assingment#1]
what is your assignment question?

**Comment by HanqingWangAI** [comment]
Thanks for your interest. This is an assignment project for my data mining course and it is done.

**Comment by AhsanulIslam** [comment]
Did you do any 3d reconstruction related work?  if then please suggest to
me some blogs or website where I can learn those things. I prefer not to
suggest papers. Thanks. Regards

**Comment by HanqingWangAI** [comment]
I'm afraid I can't help a lot. I do not follow this field recently. :(

**Comment by AhsanulIslam** [comment]
Aw, I see. Thanks for the negotiation.
